### ISSUE TITLE
1.20.4 Neoforge 20.4.155 - ``Crash on startup`` / `` Crash on load``

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [MehVahdJukaar/sawmill#15]
https://mclo.gs/3NDWRBQ
![prismlauncher_RABkPygaSb 1](https://github.com/MehVahdJukaar/sawmill/assets/10351221/2a083dea-d22c-4525-ab81-c0ac90976ff8)
Only mods present.

**Comment by MehVahdJukaar** [comment]
downgrade forge for now

**Comment by P3rf3ctXZer0** [comment]
This is not really a solution. Especially since now it seems 1.20.5 is going to be skipped in favor of 1.21.0 closing this since you don't wish to upkeep 1.20.4
