### ISSUE TITLE
Can't trade with carpenter

### ISSUE THREAD

**Issue by SAGA23456** [MehVahdJukaar/sawmill#16]
I tried to trade with the carpenter villager, but he just shook his head and couldn't do it.

**Comment by MehVahdJukaar** [comment]
Are you using latest moonlight?

**Comment by SAGA23456** [comment]
yes

**Comment by MehVahdJukaar** [comment]
And this happens if you spawn a new one? Send latest.log

**Comment by SAGA23456** [comment]
No, even in existing worlds, the carpenter shakes his head and does not trade. Also, this bug only occurs with sawmill and moonlight. And the version is 1.20.1.

**Comment by MehVahdJukaar** [comment]
no i meant NOT in existing world, once a villager is created trades are set.  Still i need latest.log
