### ISSUE TITLE
Forge 47.1.3 compatibility

### ISSUE THREAD

**Issue by mikes4b22** [MehVahdJukaar/sawmill#23]
Currently trying to run Sawmill 1.2.3 on Java 1.20.1 with Forge 47.1.3 but getting the error that it requires 47.1.40+. I tried downgrading to Sawmill 1.1.1 to no avail. Is there anyway to work around this or am I SOL for now?

**Comment by MehVahdJukaar** [comment]
no it requires newest forge as an important fix, relevant to this mod, was made there. Why stick to an outdated version of forge?

**Comment by malloryhayr** [comment]
47.1.3 is the forking point of NeoForge (iirc) and is the recommended stable version for Connector, a Fabric compatibility layer for Forge.

**Comment by MehVahdJukaar** [comment]
thats right. So either get new forge of newer neoforge. Both will work!

**Comment by MehVahdJukaar** [comment]
plus they can recommend whatever version they want, if one has a bug then that's that. New versions fix bugs so thats why its required, otherwise wouldnt even boot
