### ISSUE TITLE
Outdated structures cause DFU to process every time they are loaded

### ISSUE THREAD

**Issue by Linguardium** [MehVahdJukaar/sawmill#34]
1.20-1.3.11

You have outdated structure files in your mod. This causes minecraft to try to update them every time they are loaded, leading to extra memory and cpu usage during worldgen. Please update your structures to match the mc version you are releasing for.

This should be as easy as loading them into game and re-saving them or using a mod to load them into a StructureTemplate and writing them back out to nbt.

**Comment by MehVahdJukaar** [comment]
That's odd. I created these in 1.20.1

**Comment by MehVahdJukaar** [comment]
I checked and all the structure files actualy have the highest number of datafixed schema version as possible. Somehow even newer than 1.20.1 one. This means that they are as new as they can get

**Comment by MehVahdJukaar** [comment]
Where did you even get this info?

**Comment by Linguardium** [comment]
Ah, i must have misread this one. It showed up on an initial "does not match" scan, and I must have missed it in the secondary "less than" scan i did later. Sorry for the trouble.
