### ISSUE TITLE
[1.20.1] Any version past v1.2.4 of this mod yields "invalid player data" disconnect when joining a server.

### ISSUE THREAD

**Issue by Gbergz** [MehVahdJukaar/sawmill#39]
As the title goes, when I update this mod past version v1.2.4 I can no longer can join a server. (Modpack: TNP Limitless 7). 
Instead you get disconnected with the following message "Invalid Player Data":
![ss](https://github.com/MehVahdJukaar/sawmill/assets/26634554/2fd0e6b0-15d0-4251-b225-34f43d6dcc18)

If I roll back to the version 1.2.4 of this mod, the issue no longer occurs, so I am currently avoiding updating this mod past that version due to this issue.

This issue only happens on a server. Singleplayer is fine.

## Versions
MC: 1.20.1
Forge: 47.2.17
Sawmill: 1.3.13

## Log:
https://gist.githubusercontent.com/Gbergz/3f8f2649f61a9ffc322872d945047842/raw/8528b50bb039c7f4baeb15f31861cf95eba779f7/gistfile1.txt

**-** Gbergz

**Comment by MehVahdJukaar** [comment]
Does it work without guidebook mod?

**Comment by Gbergz** [comment]
Yes it does, apparently. 🤔

**Comment by Gbergz** [comment]
So does this issue lie with Guidebook then?

**Comment by MehVahdJukaar** [comment]
Yes

**Comment by Gbergz** [comment]
Fixed in Guidebook now!

Closing.

**Comment by MehVahdJukaar** [comment]
Awesome!
