### ISSUE TITLE
[Suggestion] Sawmill Cut Sound

### ISSUE THREAD

**Issue by CatAndPaste** [MehVahdJukaar/sawmill#4]
Sound effect is based on [CC0 (public domain) sound by Samuel Gremaud (freesound.org)](https://freesound.org/people/SamuelGremaud/sounds/511738/). Although it's public domain, author's name is stored in OGG metadata.

Adapted to use in Minecraft (mono channels). Length is 0.93 s.

Waveform comparison (suggested sound is on top) with Anvil Use (second) sound and both Stonecutter Take result (3rd and 4th) sounds:
![image](https://github.com/MehVahdJukaar/sawmill/assets/85940028/5e8bd40c-4942-4f88-a4de-e65199c4467e)

Uploaded as .zip archieve since GitHub doesn't allow to upload .ogg files directly:
[sawmill_cut.zip](https://github.com/MehVahdJukaar/sawmill/files/14041818/sawmill_cut.zip)

**Comment by MehVahdJukaar** [comment]
Oh thanks you, I was going to do this next, basically last thing this mod was missing

**Comment by MehVahdJukaar** [comment]
So I think that sounds a bit too metallic. I was thinking something softer. 
I found these online but im not convinced by them either
https://www.zapsplat.com/music/handsaw-sawing-into-rotten-wood-short-scoring-action-1/
https://www.zapsplat.com/music/handsaw-sawing-wood-short-1/
