### ISSUE TITLE
Crash With ModernFix

### ISSUE THREAD

**Issue by MoonstruckDev** [MehVahdJukaar/sawmill#5]
Forge 47.2.20
1.20.1

Upon loading into a multiplayer world, I instantly get a crash

[crash-2024-01-24_20.00.07-client.txt](https://github.com/MehVahdJukaar/sawmill/files/14042626/crash-2024-01-24_20.00.07-client.txt)

my players on the server are getting this in the chat when they check inventory: 
![image](https://github.com/MehVahdJukaar/sawmill/assets/105180230/e6e02bda-764f-4684-a4ae-8858c26e783a)

I know I have a lot of mods here, I will assume culpability but this doesn't look like it's due to my extensive modlist

Furthermore, sawmill is optional but in curseforge wood good *needs* sawmill

**Comment by MoonstruckDev** [comment]
Furthermore, sawmill is optional but in curseforge wood good *needs* sawmill

**Comment by MehVahdJukaar** [comment]
you sure you got that installed on bot client and server?

**Comment by MoonstruckDev** [comment]
... I will very swiftly close this
