### ISSUE TITLE
Feature request - Bigger GUI

### ISSUE THREAD

**Issue by meeprdib** [MehVahdJukaar/sawmill#63]
I think that Sawmill's GUI is too small, as it can only display 8 (4 * 2) outputs at a time. In a modded scenario with mods that add extra uses for wood (ex: drawers or cabinets), the GUI can become quite cumbersome and crowded as you have to scroll to see the full list of items. The search function helps to alleviate this fact, but it still doesn't solve the problem of the crowded GUI, and in my opinion, it wouldn't really be a necessary feature if the screen could already facilitate more items. The vanilla stonecutter can display 15 (5 * 3) blocks in its screen, and I don't believe it suffers from the same issue as the sawmill, even in a modded scenario with extra variants.

**Comment by MehVahdJukaar** [comment]
Stonecutter width is 4 slots not 5. Same as sawmill when search bar is off amounting to 12 slots

**Comment by MehVahdJukaar** [comment]
If you want more slots there turn off the search bar and turn on the config which adds an extra 5th column
